# 配置文件版本
# 不要修改这个值
version: 6

# 服务器最多存在多少个假人
# 默认: 1000
server-limit: 1000

# 每个玩家最多创建多少个假人
# 默认: 1
player-limit: 1

# 每多少个 ticks 触发一次假人动作更新
# 这个值调的越大, 假人的动作更新越慢
# 修改这个值可能有危险, 也许会导致红石机器出问题, 请慎重!
# 默认 1, 单位 tick
tick-period: 1

# 假人名称模版
# 如果为空, 则跟随创建者的名字并且加上后缀
# 如果为其他值, 则使用该模版并且加上后缀
# 注意:
#   1. 如果包含除 英文字母、数字、下划线以外的字符，原生自带命令将不被支持
#   2. 长度超过 16 位将会被截取
name-template: ''

# 假人创建者玩家下线时是否自动下线
follow-quiting: true

# 是否检测 IP
# 如果启用, 则一个 IP 只能创建 `maximum` 个假人
# 能够避免玩家开小号疯狂创建假人
detect-ip: false

# 服务器最近 5 分钟平均 TPS 低于这个值清除所有假人
# 每 60 秒检测一次
# 默认: 0, 即不开启, 因为移除假人可能导致玩家红石机器出问题, 按需开启吧
kale-tps: 0

# 假人 uuid 种子, 可以为任何值
# 如果为空, 则取主世界的种子
# 种子能保证 uuid 生成是固定的, 也就是说每一次服务器重启第 1 个 UUID 一定是同一个, 这个值能减少第三方插件玩家档案的膨胀
# 如果你的玩家登陆时显示 "你的 UUID 已被使用", 或者日志里提示无法生成一个没有用过的 UUID, 那你可以考虑更换这个种子值
uuid-seed: ''

# 假人区块加载距离
# 默认: 0, 表示取服务器的配置的模拟距离
distance: 0

# 是否模拟登陆
# 真实的玩家登陆流程是 "预登陆" -> "登陆" -> "加入游戏", 而假人插件默认情况下跳过了这三个步骤直接生成实体, 如果设置为 true 将会模拟这三个步骤
# 因此有一些需要在 "登陆" 时生成玩家档案的插件发生异常比如 LuckPerms, 如果服务器没有出现严重的错误不需要理会这些异常, 只是这些插件无法对假人进行操作而已
# 开启也不一定能解决所有问题, 甚至可能衍生出更加奇怪的报错并且会让第三方插件生成大量的假人数据, 或者由于和一些 "新加入玩家限制行动之类的插件" 起冲突而导致假人飞走
simulate-login: false

# 避免假人生成时出生在窒息的方块
# 默认: false
avoid-suffocation: false

# 预准备命令
# 假人诞生时会以控制台的身份按顺序执行以下命令
# 你可以用这个来实现权限组的分配之类的命令
# 非正版服请避免写一些危险指令以防第三方插件没有清档被其他玩家以假人的身份登陆而利用
# 占位符:
#   %p: 假人名称
#   %u: 假人 uuid
#   %c: 创建者的名称
preparing-commands:
  - '/give %p poppy'
  - ''

# 假人销毁时执行的命令
# 与 `preparing-commands` 类似, 会在假人销毁时依次执行的命令
# 也许可以用来销毁第三方插件的档案?
# 占位符:
#   %p: 假人名称
#   %u: 假人 uuid
#   %c: 创建者的名称
destroy-commands:
  - ''
  - ''

