version: 2

# 服务器最多存在多少个假人
# 默认: 1000
server-limit: 1000

# 每个玩家最多创建多少个假人
# 默认: 1
player-limit: 1

# 每多少个 ticks 触发一次假人动作更新
# 这个值调的越大, 假人的动作更新越慢
# 默认 1, 单位 tick
tick-period: 1

# 假人创建者玩家下线时是否自动下线
follow-quiting: true

# 是否检测 IP
# 如果启用, 则一个 IP 只能创建 `maximum` 个假人
# 能够避免玩家开小号疯狂创建假人
detect-ip: false

# 服务器最近 5 分钟平均 TPS 低于这个值清除所有假人
# 每 60 秒检测一次
# 默认: 0, 即不开启, 因为移除假人可能导致玩家炸机器, 按需开启吧
kale-tps: 0

# 假人不定时胡言乱语
# 每 8192 ticks(大约 6 分钟) 有 1/2 的几率胡言乱语
nonsense:
  - 当个假人好累啊
  - 能不能给个凳子坐坐？
  - 靠，这里蚊子有点多
  - 腐竹，救我！我动不了了
  - 能不能让我玩会生存？
  - 你好，我是学生，v我50可以吗
  - 服务器将在 5 秒钟清除垃圾，请小心手上的物品 (
  - 你们卡吗，我怎么动不了了
  - 能不能在我这里建个挂机池？
  - 汤姆哥有点小帅
