name: fakeplayer
version: '${project.version}'
main: io.github.hello09x.fakeplayer.Main
api-version: '1.20'
author: hello09x

commands:
  fakeplayer:
    description: '假人相关命令'
    usage: §2/fp ? for more info
    aliases:
      - fp

permissions:
  fakeplayer.all:
    description: '假人所有基础权限'
    children:
      - fakeplayer.spawn
      - fakeplayer.tp
    default: op

  fakeplayer.spawn:
    description: '假人创建权限'
    default: op

  fakeplayer.tp:
    description: '假人传送权限'
    default: op

  fakeplayer.admin:
    description: '假人管理员权限'
    default: op
