name: fakeplayer
version: '${project.version}'
main: io.github.hello09x.fakeplayer.Main
api-version: '1.20'
author: hello09x

commands:
  fakeplayer:
    description: '假人相关命令'
    usage: §2/fp ? for more info
    aliases:
      - fp

permissions:
  fakeplayer.all:
    description: '假人所有基础权限'
    children:
      - fakeplayer.spawn
      - fakeplayer.tp
      - fakeplayer.control
    default: op

  fakeplayer.spawn:
    description: '拥有 create, kick, list 命令执行的权限'
    default: op

  fakeplayer.tp:
    description: '拥有 tp, tphere, tps 命令执行的权限'
    default: op

  fakeplayer.control:
    description: '拥有 invsee, drop 命令执行的权限'
    default: op

  fakeplayer.admin:
    description: '假人管理员权限'
    default: op
