name: fakeplayer
version: '${project.version}'
main: io.github.hello09x.fakeplayer.Main
api-version: '1.20'
author: hello09x

permissions:
  fakeplayer.all:
    description: '假人所有基础权限'
    children:
      - fakeplayer.spawn
      - fakeplayer.tp
      - fakeplayer.profile
      - fakeplayer.exp
      - fakeplayer.action
    default: op

  fakeplayer.spawn:
    description: '拥有 spawn, kill, list 命令权限'
    default: op

  fakeplayer.spawn.location:
    description: '使用 spawn 命令时可以指定出生点'
    default: op

  fakeplayer.spawn.name:
    description: '使用 spawn 命令时可以指定假人名称'
    default: op

  fakeplayer.tp:
    description: '拥有 tp, tphere, tps 命令权限'
    default: op

  fakeplayer.profile:
    description: '拥有 health, exp 命令权限'
    default: op

  fakeplayer.action:
    description: '拥有 drop, dropinv, sneak, look, move, jump, attack, use 命令权限'
    default: op

  fakeplayer.exp:
    description: '拥有 expme 命令权限'
    default: op

  fakeplayer.cmd:
    description: '拥有 cmd 命令权限'
    default: op

  fakeplayer.admin:
    description: '假人管理员命令权限'
    default: op
